### ISSUE TITLE
GuzzleHttpAdapter InvalidBody() deprecated

### ISSUE THREAD

**Issue by skaisser** [softr/asaas-php-sdk#1]
Ao utilizar O SDK com GuzzleHttpd, Aparece o seguinte erro:

Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or a the "multipart" request option to send a multipart/form-data request.

**Comment by aldoanizio** [comment]
Valew pelo teste. Corrigido!
