### ISSUE TITLE
How to include all asaas sdk and Buzz file in function.php wordpress?

### ISSUE THREAD

**Issue by devanj** [softr/asaas-php-sdk#11]
Hello There,
I have some problem to include asaas sdk and buzz files in function.php in WordPress .... actually I want to use asaas functionality on different files so I need to include in function.php but It break my site.
Here are my file list which i am including on function.php

//BuZZ
require_once('asaas/Buzz/Exception/ExceptionInterface.php');
require_once('asaas/Buzz/Exception/RuntimeException.php');
require_once('asaas/Buzz/Client/ClientInterface.php');
require_once('asaas/Buzz/Client/AbstractClient.php');
require_once('asaas/Buzz/Client/AbstractCurl.php');
require_once('asaas/Buzz/Client/AbstractStream.php');
require_once('asaas/Buzz/Client/BatchClientInterface.php');

require_once('asaas/Buzz/Client/Curl.php');
require_once('asaas/Buzz/Client/FileGetContents.php');
require_once('asaas/Buzz/Client/MultiCurl.php');

require_once('asaas/Buzz/Exception/ClientException.php');

require_once('asaas/Buzz/Exception/InvalidArgumentException.php');
require_once('asaas/Buzz/Exception/LogicException.php');
require_once('asaas/Buzz/Exception/RequestException.php');

require_once('asaas/Buzz/Listener/ListenerInterface.php');
require_once('asaas/Buzz/Listener/History/Entry.php');
require_once('asaas/Buzz/Listener/History/Journal.php');
require_once('asaas/Buzz/Listener/BasicAuthListener.php');
require_once('asaas/Buzz/Listener/CallbackListener.php');
require_once('asaas/Buzz/Listener/CookieListener.php');
require_once('asaas/Buzz/Listener/DigestAuthListener.php');
require_once('asaas/Buzz/Listener/HistoryListener.php');
require_once('asaas/Buzz/Listener/ListenerChain.php');

require_once('asaas/Buzz/Listener/LoggerListener.php');

require_once('asaas/Buzz/Message/Factory/FactoryInterface.php');
require_once('asaas/Buzz/Message/Factory/Factory.php');

require_once('asaas/Buzz/Message/MessageInterface.php');
require_once('asaas/Buzz/Message/AbstractMessage.php');
require_once('asaas/Buzz/Message/RequestInterface.php');
require_once('asaas/Buzz/Message/Request.php');
require_once('asaas/Buzz/Message/Form/FormRequestInterface.php');
require_once('asaas/Buzz/Message/Form/FormRequest.php');
require_once('asaas/Buzz/Message/Form/FormUploadInterface.php');
require_once('asaas/Buzz/Message/Form/FormUpload.php');

require_once('asaas/Buzz/Message/Response.php');

require_once('asaas/Buzz/Util/Cookie.php');
require_once('asaas/Buzz/Util/CookieJar.php');
require_once('asaas/Buzz/Util/Url.php');

require_once('asaas/Buzz/Browser.php');

/**_assass**_**/
require_once('asaas/src/Adapter/AdapterInterface.php');
require_once('asaas/src/Adapter/BuzzAdapter.php');
require_once('asaas/src/Adapter/BuzzAsaasAuthListener.php');
require_once('asaas/src/Adapter/GuzzleAdapter.php');
require_once('asaas/src/Adapter/GuzzleHttpAdapter.php');
require_once('asaas/src/Api/AbstractApi.php');
require_once('asaas/src/Api/City.php');
require_once('asaas/src/Api/Customer.php');
require_once('asaas/src/Api/Notification.php');
require_once('asaas/src/Api/Payment.php');
require_once('asaas/src/Api/Subscription.php');
require_once('asaas/src/Entity/AbstractEntity.php');
require_once('asaas/src/Entity/City.php');
require_once('asaas/src/Entity/Customer.php');
require_once('asaas/src/Entity/Installment.php');
require_once('asaas/src/Entity/Meta.php');
require_once('asaas/src/Entity/Notification.php');
require_once('asaas/src/Entity/Payment.php');
require_once('asaas/src/Entity/Subscription.php');
require_once('asaas/src/Exception/ExceptionInterface.php');
require_once('asaas/src/Exception/HttpException.php');
require_once('asaas/src/Exception/InvalidRecordException.php');

require_once('asaas/src/Asaas.php');

use Softr\Asaas\Adapter\BuzzAdapter;
use Softr\Asaas\Asaas;

Please help

Thanks In advance

**Comment by aldoanizio** [comment]
When you include all this files in your function.php wich errors shows up ?

**Comment by devanj** [comment]
Nothing shows up ......

**Comment by aldoanizio** [comment]
Maybe your error directives are disabled. Try to include this at the top of your function.php

ini_set('display_errors', true);

So we can check wich errors are being generated.

**Comment by aldoanizio** [comment]
If this changes does not take effect check your PHP configuration and try to enable error display.

If there are anykind of errors it will shows up.

**Comment by aldoanizio** [comment]
Since there was no reply on the past 15 days I'm closing the Issue. Please feel free to reopen it if you have another doubt.
