### ISSUE TITLE
Tag 1.0

### ISSUE THREAD

**Issue by skaisser** [softr/asaas-php-sdk#3]
Amigo, Tenho testado seu código e está tudo funcionando maravilhosamente bem, Seria possivel você lançar o release no caso tag como 1.0 assim quando mexer em algo não vai bugar os sites que estão utilizando.

Pos atualmente estamos usando em dev-master via composer.

**Comment by aldoanizio** [comment]
Opa. Vou entrar em contato com o pessoal do Asaas e verificar se há a intenção de acrescentar alguma outra funcionalidade de imediato e caso não tenham nada em vista já podemos manter essa versão como 1.0 stable sem problemas.

Desde já agradeço pela colaboração.

Abraços.

**Comment by skaisser** [comment]
Eu que agradeço pelo seu excelente trabalho, Abs!
